# Vector Operations
In this we will discuss different vector operations like additions, subtractions, dot product, and cross products <br>

Before let's define two column vectors $a_1$ and $a_2$ on which we will perform bunch of operations
$$ a_1 = \begin{bmatrix} x_1 \\ y_1 \end{bmatrix} $$ $$ \\b_1 = \begin{bmatrix} x_2 \\ y_2 \end{bmatrix} $$

In [1]:
#import numpy module
import numpy as np

In [2]:
#now lets see an example
a_1 = [[1],[2]]
a_1 = np.array(a_1)
a_1 = a_1.reshape((2,1))
a_1

array([[1],
       [2]])

In [3]:
a_2 = [[3],[4]]
a_2 = np.array(a_2)
a_2 = a_2.reshape((2,1))
a_2

array([[3],
       [4]])

## Addition
Now the addition of two vectors $$ a = a_1 + a_2 $$ which can be written as $$ a = \begin{bmatrix} x_1 \\ y_1 \end{bmatrix} + \begin{bmatrix} x_2 \\ y_2 \end{bmatrix} $$ which can be further evaluated as $$ a = \begin{bmatrix} x_1 + x_2 \\ y_1 + y_2 \end{bmatrix} $$

In [4]:
# Now in case of numpy arrays 
# addition is done by simply adding the two vectors 
a = a_1 + a_2
a

array([[4],
       [6]])